"""Add unique constraint to portfolio user_id

Revision ID: 01e28daf1322
Revises: 707fc5ea2060
Create Date: 2025-08-13 17:49:05.790943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e28daf1322'
down_revision: Union[str, None] = '707fc5ea2060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_portfolios_user_id', table_name='portfolios')
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.create_index('ix_portfolios_user_id', 'portfolios', ['user_id'], unique=False)
    # ### end Alembic commands ###
